services:
  caddy:
    image: caddy:alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./html:/var/www/html
    restart: always
    networks:
      - wp

  php:
    build: ./php
    container_name: php
    restart: always
    volumes:
      - ./html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - wp

  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: strong_root_pass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: strong_pass
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - wp

  redis:
    image: redis:7-alpine
    container_name: redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    networks:
      - wp

  adminneo:
    image: adminneoorg/adminneo
    container_name: adminneo
    restart: always
    ports:
      - "127.0.0.1:8080:8080"

    depends_on:
      - mariadb

    networks:
      - wp

networks:
  wp:
